import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

// Le mot de passe en clair qui sera utilisé pour TOUS les comptes entreprise créés.
const MOT_DE_PASSE_POUR_TEST = 'password123';

const companiesData = [
  // --- Technologie ---
  {
    name: "Google",
    email: "contact@google.com",
    secteurActivite: "Technologies de l'information",
    adresse: "1600 Amphitheatre Parkway, Mountain View, CA 94043, USA",
    siteWeb: "https://about.google/",
    description: "Entreprise technologique spécialisée dans les services et produits liés à Internet.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
    raisonSociale: "Organiser l'information à l'échelle mondiale et la rendre universellement accessible et utile.",
    dateDeCreation: new Date("1998-09-04"),
    certifications: ["ISO 27001", "SOC 2 Type II"],
    servicesProposes: ["Recherche en ligne", "Publicité", "Cloud Computing", "Logiciels"],
    nombreEmployes: 200000,
    horairesOuverture: "24/7 (services en ligne)",
    pays: "États-Unis",
    ville: "Mountain View",
    sites: ["Mountain View, USA", "Zurich, Suisse", "Paris, France"],
    contacts: ["+1 650-253-0000"],
    images: ["https://suindependent.com/wp-content/uploads/2018/03/Google-office.jpg"],
  },
  {
    name: "Microsoft",
    email: "info@microsoft.com",
    secteurActivite: "Logiciels et services informatiques",
    adresse: "One Microsoft Way, Redmond, WA 98052, USA",
    siteWeb: "https://www.microsoft.com",
    description: "Développe, fabrique, licencie et vend des logiciels informatiques, de l'électronique grand public, des ordinateurs personnels et des services.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
    raisonSociale: "Donner à chaque personne et à chaque organisation les moyens de ses ambitions.",
    dateDeCreation: new Date("1975-04-04"),
    certifications: ["Azure Compliance", "Microsoft Trust Center"],
    servicesProposes: ["Windows", "Office 365", "Azure", "Xbox"],
    nombreEmployes: 221000,
    horairesOuverture: "9:00 - 17:00 (bureaux)",
    pays: "États-Unis",
    ville: "Redmond",
    sites: ["Redmond, USA", "Dublin, Irlande"],
    contacts: ["+1 425-882-8080"],
    images: ["https://news.microsoft.com/wp-content/uploads/2017/09/Building-92-Cafe-960x640.jpg"],
  },
  // --- Automobile ---
  {
    name: "Toyota",
    email: "relations@toyota.jp",
    secteurActivite: "Construction automobile",
    adresse: "1 Toyota-cho, Toyota City, Aichi Prefecture 471-8571, Japon",
    siteWeb: "https://global.toyota/",
    description: "Constructeur automobile multinational japonais, l'un des plus grands au monde.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Toyota_logo.svg",
    raisonSociale: "Produire le bonheur pour tous.",
    dateDeCreation: new Date("1937-08-28"),
    certifications: ["ISO 14001"],
    servicesProposes: ["Vente de véhicules", "Services financiers", "Entretien"],
    nombreEmployes: 375000,
    horairesOuverture: "8:30 - 17:30 (siège social)",
    pays: "Japon",
    ville: "Toyota",
    sites: ["Toyota, Japon", "Georgetown, USA", "Valenciennes, France"],
    contacts: ["+81 565-28-2121"],
    images: ["https://global.toyota/pages/news/images/2019/11/05/1100/20191105_02_01.jpg"],
  },
  // --- Distribution ---
  {
    name: "Carrefour",
    email: "contact@carrefour.com",
    secteurActivite: "Grande distribution",
    adresse: "93 Avenue de Paris, 91300 Massy, France",
    siteWeb: "https://www.carrefour.com",
    description: "Groupe français du secteur de la grande distribution.",
    logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/3/3b/Logo_Carrefour.svg/1200px-Logo_Carrefour.svg.png",
    raisonSociale: "Assurer la transition alimentaire pour tous.",
    dateDeCreation: new Date("1959-01-01"),
    certifications: ["Label Rouge", "Bio"],
    servicesProposes: ["Vente de produits", "Services bancaires", "Voyages"],
    nombreEmployes: 321000,
    horairesOuverture: "8:30 - 21:30 (magasins)",
    pays: "France",
    ville: "Massy",
    sites: ["Massy, France", "Madrid, Espagne", "São Paulo, Brésil", "Douala, Cameroun"],
    contacts: ["+33 1 64 50 50 50"],
    images: ["https://upload.wikimedia.org/wikipedia/commons/2/23/Carrefour_City_Angers_Ralliement.jpg"],
  },
  // --- Énergie ---
  {
    name: "TotalEnergies",
    email: "info@totalenergies.com",
    secteurActivite: "Énergie",
    adresse: "2 Place Jean Millier, 92400 Courbevoie, France",
    siteWeb: "https://totalenergies.com",
    description: "Compagnie multi-énergies qui produit et commercialise pétrole, biocarburants, gaz naturel, renouvelables et électricité.",
    logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/6/62/TotalEnergies_logo.svg/1200px-TotalEnergies_logo.svg.png",
    raisonSociale: "Devenir un acteur majeur de la transition énergétique.",
    dateDeCreation: new Date("1924-03-28"),
    certifications: ["ISO 50001"],
    servicesProposes: ["Exploration-production", "Raffinage", "Distribution", "Électricité renouvelable"],
    nombreEmployes: 105000,
    horairesOuverture: "9:00 - 18:00 (siège social)",
    pays: "France",
    ville: "Courbevoie",
    sites: ["Courbevoie, France", "Houston, USA", "Port Harcourt, Nigeria"],
    contacts: ["+33 1 47 44 45 46"],
    images: ["https://media.lesechos.com/api/v1/images/view/61e05d76d2916b3f7f225573/1280x720/070500127261-web-v2/tour-totalenergies-a-la-defense.jpg"],
  },
  // --- Industrie ---
  {
    name: "Siemens",
    email: "info@siemens.com",
    secteurActivite: "Technologies industrielles",
    adresse: "Werner-von-Siemens-Straße 1, 80333 Munich, Allemagne",
    siteWeb: "https://www.siemens.com",
    description: "Groupe technologique allemand axé sur l'industrie, les infrastructures, les transports et la santé.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Siemens-logo.svg/1280px-Siemens-logo.svg.png",
    raisonSociale: "Technology to Transform the Everyday.",
    dateDeCreation: new Date("1847-10-12"),
    certifications: ["TÜV SÜD", "ISO 9001"],
    servicesProposes: ["Automatisation industrielle", "Technologies du bâtiment", "Solutions de mobilité", "Équipements médicaux"],
    nombreEmployes: 320000,
    horairesOuverture: "8:00 - 17:00 (bureaux)",
    pays: "Allemagne",
    ville: "Munich",
    sites: ["Munich, Allemagne", "Berlin, Allemagne", "Shanghai, Chine"],
    contacts: ["+49 89 63600"],
    images: ["https://assets.new.siemens.com/siemens/assets/api/uuid:4065675f-7589-4b69-96a2-9b4563854d92/width:1920/quality:high/siemens-campus-erlangen.jpg"],
  },
  // --- Électronique ---
  {
    name: "Samsung",
    email: "support@samsung.com",
    secteurActivite: "Électronique grand public",
    adresse: "1320-10 Seocho 2(i)-dong, Seocho-gu, Séoul, Corée du Sud",
    siteWeb: "https://www.samsung.com",
    description: "Conglomérat multinational sud-coréen spécialisé dans l'électronique, la téléphonie et l'électroménager.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Samsung_Logo.svg/1280px-Samsung_Logo.svg.png",
    raisonSociale: "Inspire the World, Create the Future.",
    dateDeCreation: new Date("1938-03-01"),
    certifications: ["TCO Certified", "EPEAT"],
    servicesProposes: ["Smartphones", "Télévisions", "Électroménager", "Puces mémoire"],
    nombreEmployes: 270000,
    horairesOuverture: "9:00 - 18:00 (bureaux)",
    pays: "Corée du Sud",
    ville: "Séoul",
    sites: ["Séoul, Corée du Sud", "Austin, USA", "Hanoï, Vietnam"],
    contacts: ["+82 2-2255-0114"],
    images: ["https://images.samsung.com/is/image/samsung/assets/global/about-us/our-business/digital-city/DSC_3389-S.jpg"],
  },
  // --- Luxe ---
  {
    name: "LVMH",
    email: "contact@lvmh.com",
    secteurActivite: "Luxe",
    adresse: "22 Avenue Montaigne, 75008 Paris, France",
    siteWeb: "https://www.lvmh.fr",
    description: "Leader mondial de l'industrie du luxe, présent dans les secteurs de la mode, maroquinerie, vins & spiritueux, parfums & cosmétiques, et montres & joaillerie.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/LVMH-Logo.svg/1200px-LVMH-Logo.svg.png",
    raisonSociale: "Promouvoir un art de vivre raffiné.",
    dateDeCreation: new Date("1987-06-03"),
    certifications: ["Responsible Jewellery Council (RJC)"],
    servicesProposes: ["Mode et Maroquinerie", "Vins et Spiritueux", "Parfums et Cosmétiques"],
    nombreEmployes: 196000,
    horairesOuverture: "9:30 - 18:30 (siège social)",
    pays: "France",
    ville: "Paris",
    sites: ["Paris, France", "New York, USA", "Genève, Suisse"],
    contacts: ["+33 1 44 13 22 22"],
    images: ["https://www.lvmh.fr/wp-content/uploads/2021/08/samaritaine-facade-nuit-2-scaled.jpg"],
  },
  // --- Agroalimentaire ---
  {
    name: "Nestlé",
    email: "investor.relations@nestle.com",
    secteurActivite: "Industrie agroalimentaire",
    adresse: "Avenue Nestlé 55, 1800 Vevey, Suisse",
    siteWeb: "https://www.nestle.com",
    description: "Multinationale suisse et l'une des principales entreprises agroalimentaires au monde.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Nestle.svg/1024px-Nestle.svg.png",
    raisonSociale: "Good food, Good life.",
    dateDeCreation: new Date("1866-01-01"),
    certifications: ["Rainforest Alliance", "Fairtrade"],
    servicesProposes: ["Café", "Produits laitiers", "Nutrition infantile", "Aliments pour animaux"],
    nombreEmployes: 275000,
    horairesOuverture: "8:00 - 17:00 (siège social)",
    pays: "Suisse",
    ville: "Vevey",
    sites: ["Vevey, Suisse", "Arlington, USA", "Issy-les-Moulineaux, France"],
    contacts: ["+41 21 924 21 11"],
    images: ["https://www.nestle.com/sites/default/files/styles/full_width_image_1920x795_/public/2022-02/sustainability-packaging-testing-institute.jpg"],
  },
  // --- Conglomérat Africain ---
  {
    name: "Dangote Group",
    email: "info@dangote.com",
    secteurActivite: "Conglomérat industriel",
    adresse: "Union Marble House, 1 Alfred Rewane Rd, Ikoyi, Lagos, Nigeria",
    siteWeb: "https://www.dangote.com/",
    description: "Conglomérat multinational nigérian, fondé par Aliko Dangote. Le groupe est l'un des plus grands de l'Afrique de l'Ouest.",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/58/Dangote_Group_Logo.svg/1200px-Dangote_Group_Logo.svg.png",
    raisonSociale: "Toucher la vie des gens en leur fournissant leurs besoins de base.",
    dateDeCreation: new Date("1981-01-01"),
    certifications: ["ISO 9001:2008", "SON (Standards Organisation of Nigeria)"],
    servicesProposes: ["Ciment", "Sucre", "Farine", "Pétrochimie"],
    nombreEmployes: 30000,
    horairesOuverture: "8:00 - 17:00 (bureaux)",
    pays: "Nigeria",
    ville: "Lagos",
    sites: ["Lagos, Nigeria", "Accra, Ghana", "Douala, Cameroun"],
    contacts: ["+234 1 448 0815"],
    images: ["https://www.dangote.com/wp-content/uploads/2019/01/DSC_0118-min.jpg"],
  },
  // --- ===ENTREPRISES CAMEROUNAISES=== ---
  {
    name: "MTN Cameroon",
    email: "contact@mtn.cm",
    secteurActivite: "Télécommunications",
    adresse: "Rue de l'Hôtel de Ville, Bonanjo, Douala, Cameroun",
    siteWeb: "https://www.mtn.cm",
    description: "Leader du marché des télécommunications au Cameroun, offrant des services de téléphonie mobile, d'internet et de Mobile Money.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/MTN_logo_-_2022.svg/1200px-MTN_logo_-_2022.svg.png",
    raisonSociale: "Connecter les Camerounais à un avenir meilleur et audacieux.",
    dateDeCreation: new Date("2000-02-15"),
    certifications: ["ISO 9001:2015"],
    servicesProposes: ["Forfaits mobiles", "Internet 4G/5G", "MTN Mobile Money", "Solutions d'entreprise"],
    nombreEmployes: 1500,
    horairesOuverture: "8:00 - 17:00 (agences)",
    pays: "Cameroun",
    ville: "Douala",
    sites: ["Douala (Siège)", "Yaoundé", "Bafoussam", "Garoua"],
    contacts: ["+237 8022"],
    images: ["https://investiraucameroun.com/images/stories/2020/09/mtn-cameroun_2.jpg"],
  },
  {
    name: "SABC (Brasseries du Cameroun)",
    email: "info@lesbrasseriesducameroun.com",
    secteurActivite: "Agroalimentaire & Boissons",
    adresse: "BP 4036, Douala, Cameroun",
    siteWeb: "https://www.lesbrasseriesducameroun.com/",
    description: "Leader de l'industrie brassicole et des boissons gazeuses au Cameroun.",
    logo: "https://www.lesbrasseriesducameroun.com/images/logo-sabg-groupe_1.png",
    raisonSociale: "Désaltérer et rafraîchir le Cameroun avec des produits de qualité.",
    dateDeCreation: new Date("1948-02-03"),
    certifications: ["ISO 22000"],
    servicesProposes: ["Bières", "Boissons gazeuses", "Eau minérale"],
    nombreEmployes: 3000,
    horairesOuverture: "7:30 - 17:00 (bureaux)",
    pays: "Cameroun",
    ville: "Douala",
    sites: ["Douala", "Yaoundé", "Bafoussam", "Garoua", "Limbé"],
    contacts: ["+237 2 33 50 17 00"],
    images: ["https://www.lesbrasseriesducameroun.com/images/un-demi-siecle-de-succes-stories_1.jpg"],
  },
  {
    name: "Orange Cameroun",
    email: "serviceclient@orange.cm",
    secteurActivite: "Télécommunications",
    adresse: "Boulevard de la Liberté, Akwa, Douala, Cameroun",
    siteWeb: "https://www.orange.cm",
    description: "Opérateur majeur de télécommunications, fournisseur de services mobiles, internet et de paiement mobile.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Orange_logo.svg/1200px-Orange_logo.svg.png",
    raisonSociale: "Être l'opérateur qui vous rapproche de l'essentiel.",
    dateDeCreation: new Date("1999-01-01"),
    certifications: [],
    servicesProposes: ["Téléphonie mobile", "Fibre optique", "Orange Money", "Cloud"],
    nombreEmployes: 1200,
    horairesOuverture: "8:00 - 17:00 (agences)",
    pays: "Cameroun",
    ville: "Douala",
    sites: ["Douala", "Yaoundé", "Maroua"],
    contacts: ["+237 950"],
    images: ["https://www.digitalbusiness.africa/wp-content/uploads/2020/07/Siege-Orange-Cameroun-Douala.jpg"],
  },
  {
    name: "Eneo Cameroon",
    email: "info@eneocameroon.cm",
    secteurActivite: "Énergie & Services Publics",
    adresse: "Avenue du Général de Gaulle, Bonanjo, Douala, Cameroun",
    siteWeb: "https://eneocameroon.cm/",
    description: "Principal opérateur du secteur de l'électricité au Cameroun, en charge de la production et de la distribution.",
    logo: "https://eneocameroon.cm/images/logo_Eneo.png",
    raisonSociale: "Fournir une énergie fiable et un service de qualité, en toute sécurité.",
    dateDeCreation: new Date("2014-01-01"),
    certifications: [],
    servicesProposes: ["Production d'électricité", "Distribution d'électricité", "Services à la clientèle"],
    nombreEmployes: 3700,
    horairesOuverture: "7:30 - 15:30 (agences)",
    pays: "Cameroun",
    ville: "Douala",
    sites: ["Douala", "Yaoundé", "Bertoua"],
    contacts: ["+237 8010"],
    images: ["https://www.businessincameroon.com/images/stories/2017/04/Eneo-Cameroon.png"],
  },
  {
    name: "Afriland First Bank",
    email: "afriland@afrilandfirstbank.com",
    secteurActivite: "Banque & Finance",
    adresse: "Place de l'Indépendance, Bonanjo, Yaoundé, Cameroun",
    siteWeb: "https://www.afrilandfirstbank.com",
    description: "Banque commerciale de premier plan au Cameroun avec une forte présence en Afrique.",
    logo: "https://www.afrilandfirstbank.com/wp-content/uploads/2022/04/logo-afriland.png",
    raisonSociale: "Promouvoir l'émergence d'une nouvelle Afrique.",
    dateDeCreation: new Date("1987-01-01"),
    certifications: ["COBAC"],
    servicesProposes: ["Comptes courants", "Crédits", "Transferts d'argent", "Monétique"],
    nombreEmployes: 1000,
    horairesOuverture: "8:00 - 17:00",
    pays: "Cameroun",
    ville: "Yaoundé",
    sites: ["Yaoundé", "Douala", "Bafoussam"],
    contacts: ["+237 2 22 23 32 69"],
    images: ["https://www.afrilandfirstbank.com/wp-content/uploads/2022/04/Afriland-First-Bank-Siege-Yaounde.jpg"],
  },
  {
    name: "SCDP",
    email: "contact@scdp.cm",
    secteurActivite: "Pétrole & Gaz",
    adresse: "BP 2315, Douala, Cameroun",
    siteWeb: "http://www.scdp.cm/",
    description: "Société Camerounaise de Dépôts Pétroliers, en charge du stockage et de la distribution des produits pétroliers sur le territoire national.",
    logo: "http://www.scdp.cm/wp-content/uploads/2021/08/cropped-logo-scdp.jpg",
    raisonSociale: "Garantir la disponibilité des produits pétroliers sur l'ensemble du territoire.",
    dateDeCreation: new Date("1978-01-01"),
    certifications: [],
    servicesProposes: ["Stockage de produits pétroliers", "Logistique", "Distribution"],
    nombreEmployes: 500,
    horairesOuverture: "7:30 - 17:30",
    pays: "Cameroun",
    ville: "Douala",
    sites: ["Douala", "Yaoundé", "Bafoussam", "Limbe"],
    contacts: ["+237 2 33 40 54 45"],
    images: ["http://www.scdp.cm/wp-content/uploads/2021/08/scdp-slider1.jpg"],
  },
  {
    name: "Chococam",
    email: "info@chococam.com",
    secteurActivite: "Agroalimentaire",
    adresse: "Zone Industrielle de Bassa, Douala, Cameroun",
    siteWeb: "https://chococam.com/",
    description: "Filiale du groupe Tiger Brands, leader de la confiserie et du chocolat au Cameroun.",
    logo: "https://chococam.com/wp-content/uploads/2022/02/LOGO-CHOCOCAM-TIGER-BRANDS-BLEU-ET-ROUGE-300x129.png",
    raisonSociale: "Nourrir et prendre soin des vies chaque jour.",
    dateDeCreation: new Date("1965-01-01"),
    certifications: ["ISO 9001"],
    servicesProposes: ["Confiserie", "Chocolat", "Pâtes à tartiner"],
    nombreEmployes: 600,
    horairesOuverture: "8:00 - 17:00",
    pays: "Cameroun",
    ville: "Douala",
    sites: ["Douala"],
    contacts: ["+237 2 33 37 02 44"],
    images: ["https://chococam.com/wp-content/uploads/2022/03/Chococam-scaled.jpg"],
  },

  // --- ===AUTRES ENTREPRISES AFRICAINES=== ---
  {
    name: "Jumia",
    email: "press@jumia.com",
    secteurActivite: "E-commerce & Marketplace",
    adresse: "Lagos, Nigeria (Opérations panafricaines)",
    siteWeb: "https://group.jumia.com/",
    description: "Plateforme de commerce électronique de premier plan en Afrique, opérant dans plus de 10 pays.",
    logo: "https://group.jumia.com/wp-content/uploads/2022/07/Jumia-Logo.png",
    raisonSociale: "Connecter les consommateurs et les entrepreneurs pour améliorer leur vie.",
    dateDeCreation: new Date("2012-01-01"),
    certifications: [],
    servicesProposes: ["Vente en ligne", "Jumia Food", "JumiaPay"],
    nombreEmployes: 5000,
    horairesOuverture: "24/7 (plateforme en ligne)",
    pays: "Nigeria",
    ville: "Lagos",
    sites: ["Lagos, Nigeria", "Le Caire, Égypte", "Nairobi, Kenya", "Abidjan, Côte d'Ivoire"],
    contacts: [],
    images: ["https://african.business/wp-content/uploads/2019/04/Jumia-IPO.jpg"],
  },
  {
    name: "Safaricom",
    email: "prcomms@safaricom.co.ke",
    secteurActivite: "Télécommunications",
    adresse: "Safaricom House, Waiyaki Way, Nairobi, Kenya",
    siteWeb: "https://www.safaricom.co.ke/",
    description: "Principal fournisseur de services de télécommunications au Kenya, pionnier du paiement mobile avec M-PESA.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/23/Safaricom_Logo.svg",
    raisonSociale: "Transformer des vies.",
    dateDeCreation: new Date("1997-01-01"),
    certifications: [],
    servicesProposes: ["Services mobiles", "M-PESA", "Internet Fibre"],
    nombreEmployes: 6000,
    horairesOuverture: "8:00 - 17:00 (bureaux)",
    pays: "Kenya",
    ville: "Nairobi",
    sites: ["Nairobi", "Mombasa", "Kisumu"],
    contacts: ["+254 722 000000"],
    images: ["https://www.safaricom.co.ke/images/safaricom-hq.jpg"],
  },
  {
    name: "OCP Group",
    email: "contact@ocpgroup.ma",
    secteurActivite: "Industrie minière",
    adresse: "2-4 Rue Al Abtal, Hay Erraha, Casablanca, Maroc",
    siteWeb: "https://www.ocpgroup.ma/",
    description: "Leader mondial sur le marché du phosphate et de ses dérivés, notamment les engrais.",
    logo: "https://www.ocpgroup.ma/sites/default/files/logo-ocp.png",
    raisonSociale: "Nourrir la terre pour nourrir la planète.",
    dateDeCreation: new Date("1920-01-01"),
    certifications: ["ISO 45001"],
    servicesProposes: ["Extraction de phosphate", "Production d'acide phosphorique", "Fabrication d'engrais"],
    nombreEmployes: 21000,
    horairesOuverture: "8:30 - 18:30",
    pays: "Maroc",
    ville: "Casablanca",
    sites: ["Casablanca", "Jorf Lasfar", "Khouribga"],
    contacts: ["+212 5 22 23 20 25"],
    images: ["https://www.ocpgroup.ma/sites/default/files/styles/1130x500/public/2021-02/ocp-group-safi-industrial-complex.jpg"],
  },
  {
    name: "Ethiopian Airlines",
    email: "info@ethiopianairlines.com",
    secteurActivite: "Transport aérien",
    adresse: "Bole International Airport, Addis Ababa, Éthiopie",
    siteWeb: "https://www.ethiopianairlines.com",
    description: "Compagnie aérienne nationale de l'Éthiopie, l'une des plus grandes et des plus rentables d'Afrique.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Ethiopian_Airlines_logo.svg/1200px-Ethiopian_Airlines_logo.svg.png",
    raisonSociale: "The New Spirit of Africa.",
    dateDeCreation: new Date("1945-12-21"),
    certifications: ["IATA, SKYTRAX 4-Star"],
    servicesProposes: ["Transport de passagers", "Fret aérien", "Maintenance aéronautique"],
    nombreEmployes: 17000,
    horairesOuverture: "24/7",
    pays: "Éthiopie",
    ville: "Addis Abeba",
    sites: ["Addis Abeba", "Lomé", "Dublin"],
    contacts: ["+251 11 665 6666"],
    images: ["https://corporate.ethiopianairlines.com/images/default-source/background-images/our-company.jpg"],
  },
  {
    name: "Standard Bank Group",
    email: "information@standardbank.co.za",
    secteurActivite: "Banque & Finance",
    adresse: "5 Simmonds Street, Johannesburg, 2001, Afrique du Sud",
    siteWeb: "https://www.standardbank.com/",
    description: "Le plus grand groupe bancaire d'Afrique en termes d'actifs.",
    logo: "https://www.standardbank.com/sbg/sites/default/files/2022-07/SB-logo.png",
    raisonSociale: "Africa is our home, we drive her growth.",
    dateDeCreation: new Date("1862-01-01"),
    certifications: [],
    servicesProposes: ["Services bancaires personnels", "Services bancaires aux entreprises", "Gestion de patrimoine"],
    nombreEmployes: 50000,
    horairesOuverture: "9:00 - 15:30 (agences)",
    pays: "Afrique du Sud",
    ville: "Johannesburg",
    sites: ["Johannesburg", "Le Cap", "Nairobi", "Lagos"],
    contacts: ["+27 860 123 000"],
    images: ["https://corporateandinvestment.standardbank.com/cib/international/about-us/-/media/cib-international/images/cib-banner-3.jpg"],
  },
  {
    name: "Sonatrach",
    email: "contact@sonatrach.dz",
    secteurActivite: "Pétrole & Gaz",
    adresse: "Djenane El Malik, Hydra, Alger, Algérie",
    siteWeb: "https://sonatrach.com/",
    description: "Compagnie nationale algérienne pour la recherche, la production, le transport, la transformation, et la commercialisation des hydrocarbures.",
    logo: "https://sonatrach.com/wp-content/uploads/2021/11/logo-sonatrach.png",
    raisonSociale: "Énergie pour un avenir meilleur.",
    dateDeCreation: new Date("1963-12-31"),
    certifications: [],
    servicesProposes: ["Pétrole brut", "Gaz naturel", "GPL", "Produits raffinés"],
    nombreEmployes: 200000,
    horairesOuverture: "8:00 - 16:30",
    pays: "Algérie",
    ville: "Alger",
    sites: ["Alger", "Hassi Messaoud", "Arzew"],
    contacts: ["+213 21 54 70 00"],
    images: ["https://sonatrach.com/wp-content/uploads/2023/07/siege-sonatrach-1-e1688640700147.jpg"],
  },
  {
    name: "Shoprite Holdings",
    email: "consumer@shoprite.co.za",
    secteurActivite: "Grande distribution",
    adresse: "Cnr William Dabs Street & Old Paarl Road, Brackenfell, 7560, Afrique du Sud",
    siteWeb: "https://www.shopriteholdings.co.za/",
    description: "Le plus grand détaillant en alimentation d'Afrique, opérant dans plusieurs pays à travers le continent.",
    logo: "https://www.shopriteholdings.co.za/etc.clientlibs/shoprite/clientlibs/clientlib-site/resources/logos/shoprite-logo-rgb.png",
    raisonSociale: "Des prix bas auxquels vous pouvez faire confiance, toujours.",
    dateDeCreation: new Date("1979-01-01"),
    certifications: [],
    servicesProposes: ["Supermarchés", "Vente en gros", "Magasins de meubles"],
    nombreEmployes: 149000,
    horairesOuverture: "8:00 - 20:00 (magasins)",
    pays: "Afrique du Sud",
    ville: "Brackenfell",
    sites: ["Brackenfell", "Lagos", "Lusaka"],
    contacts: ["+27 21 980 4000"],
    images: ["https://www.shopriteholdings.co.za/content/shoprite/en/home/media/images/gallery/in-the-store/_jcr_content/root/container/container/image.coreimg.82.1280.jpeg/1631885567305/shoprite-produce.jpeg"],
  },
  {
    name: "Ecobank",
    email: "ecobank@ecobank.com",
    secteurActivite: "Banque & Finance",
    adresse: "2365, Boulevard du Mono, Lomé, Togo",
    siteWeb: "https://ecobank.com/",
    description: "Groupe bancaire panafricain de premier plan, offrant des services bancaires de gros, de détail, d'investissement et de transaction.",
    logo: "https://ecobank.com/medias/2021/09/ecobank-logo.svg",
    raisonSociale: "Construire une banque panafricaine de classe mondiale et contribuer à l'intégration économique et financière de l'Afrique.",
    dateDeCreation: new Date("1985-01-01"),
    certifications: [],
    servicesProposes: ["Services bancaires numériques", "Prêts", "Gestion de trésorerie"],
    nombreEmployes: 13000,
    horairesOuverture: "8:00 - 16:00 (agences)",
    pays: "Togo",
    ville: "Lomé",
    sites: ["Lomé, Togo", "Lagos, Nigeria", "Accra, Ghana", "Abidjan, Côte d'Ivoire"],
    contacts: ["+228 22 21 03 23"],
    images: ["https://www.togofirst.com/media/k2/items/cache/4081c7e2956f08846f4a86f34584c784_L.jpg"],
  },
  {
      name: "Cevital",
      email: "contact@cevital.com",
      secteurActivite: "Agroalimentaire & Industrie",
      adresse: "Djamaâ El Djazaïr, Mohammadia, Alger, Algérie",
      siteWeb: "https://www.cevital.com/",
      description: "Le plus grand groupe privé d'Algérie, actif dans l'agroalimentaire, l'industrie, la logistique et la distribution.",
      logo: "https://www.cevital.com/wp-content/uploads/2021/09/logo-cevital-2.png",
      raisonSociale: "Bâtir l'avenir.",
      dateDeCreation: new Date("1971-01-01"),
      certifications: ["ISO 22000"],
      servicesProposes: ["Sucre", "Huiles végétales", "Verre plat", "Électroménager"],
      nombreEmployes: 18000,
      horairesOuverture: "8:00 - 17:00",
      pays: "Algérie",
      ville: "Alger",
      sites: ["Alger", "Béjaïa"],
      contacts: ["+213 21 89 77 77"],
      images: ["https://www.cevital.com/wp-content/uploads/2021/10/DJAMAA-EL-DJAZAIR-scaled.jpg"],
  },
  {
      name: "CIH Bank",
      email: "contact@cihbank.ma",
      secteurActivite: "Banque & Finance",
      adresse: "187, Avenue Hassan II, Casablanca, Maroc",
      siteWeb: "https://www.cihbank.ma/",
      description: "Banque marocaine innovante, fortement orientée vers la banque numérique et les services aux jeunes.",
      logo: "https://www.cihbank.ma/sites/all/themes/cih/logo.png",
      raisonSociale: "La banque d'un monde qui change.",
      dateDeCreation: new Date("1920-01-01"),
      certifications: [],
      servicesProposes: ["Comptes gratuits", "Banque en ligne", "Crédits immobiliers", "Crédits à la consommation"],
      nombreEmployes: 2500,
      horairesOuverture: "8:15 - 15:45 (agences)",
      pays: "Maroc",
      ville: "Casablanca",
      sites: ["Casablanca", "Rabat", "Marrakech"],
      contacts: ["+212 5 22 47 90 00"],
      images: ["https://www.cihbank.ma/sites/default/files/styles/1080x560/public/2021-08/1.jpg"],
  },
  {
      name: "KCB Group",
      email: "contactcentre@kcbgroup.com",
      secteurActivite: "Banque & Finance",
      adresse: "Kencom House, Moi Avenue, Nairobi, Kenya",
      siteWeb: "https://kcbgroup.com/",
      description: "Institution financière de premier plan en Afrique de l'Est, offrant une large gamme de services financiers.",
      logo: "https://kcbgroup.com/wp-content/uploads/2021/08/kcb-logo.png",
      raisonSociale: "Go Ahead.",
      dateDeCreation: new Date("1896-01-01"),
      certifications: [],
      servicesProposes: ["Services bancaires", "Assurances", "Gestion d'investissements"],
      nombreEmployes: 7500,
      horairesOuverture: "8:30 - 16:00 (agences)",
      pays: "Kenya",
      ville: "Nairobi",
      sites: ["Nairobi, Kenya", "Kigali, Rwanda", "Dar es Salaam, Tanzanie"],
      contacts: ["+254 711 087000"],
      images: ["https://kcbgroup.com/wp-content/uploads/2023/11/kcb-convention-center.jpg"],
  }
];

async function main() {
  console.log("Start seeding ...");
  
  const hashedPassword = await bcrypt.hash(MOT_DE_PASSE_POUR_TEST, 10);

  for (const company of companiesData) {
    // Vérifier si l'utilisateur existe déjà pour éviter les erreurs d'email unique
    const existingUser = await prisma.user.findUnique({
      where: { email: company.email },
    });

    if (existingUser) {
      console.log(`User ${company.name} already exists, skipping.`);
      continue;
    }

    // 1. Créer l'utilisateur associé
    const newUser = await prisma.user.create({
      data: {
        name: company.name,
        email: company.email,
        mot_de_passe: hashedPassword,
        type: 'entreprise',
        emailVerified: new Date(),
      },
    });

    // 2. Créer l'entreprise en la liant à l'utilisateur
    await prisma.entreprise.create({
      data: {
        userId: newUser.id,
        secteur_activite: company.secteurActivite,
        adresse: company.adresse,
        site_web: company.siteWeb,
        description: company.description,
        logo: company.logo,
        raison_sociale: company.raisonSociale,
        date_de_creation: company.dateDeCreation,
        certifications: company.certifications,
        services_proposes: company.servicesProposes,
        nombre_employes: company.nombreEmployes,
        horaires_ouverture: company.horairesOuverture,
        pays: company.pays,
        ville: company.ville,
        sites: company.sites,
        contacts: company.contacts,
        images: company.images,
      },
    });

    console.log(`Created company: ${company.name}`);
  }

  console.log("Seeding finished.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });